# Generated by Django 3.2.9 on 2021-11-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy_dev_api', '0002_alter_guide_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
